"""add file_vectors table

Revision ID: 8ec66271f89a
Revises: cacf7b24df36
Create Date: 2026-03-22 14:31:53.141399

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8ec66271f89a'
down_revision: Union[str, Sequence[str], None] = 'cacf7b24df36'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('file', sa.Column('path', sa.String(), nullable=False))
    op.create_index(op.f('ix_filevector_file_id'), 'filevector', ['file_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_filevector_file_id'), table_name='filevector')
    op.drop_column('file', 'path')
    # ### end Alembic commands ###
