"""change content to text

Revision ID: cacf7b24df36
Revises: c953f31691c8
Create Date: 2026-03-15 17:24:53.087261

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cacf7b24df36'
down_revision: Union[str, Sequence[str], None] = 'c953f31691c8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('file', 'content',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('file', 'content',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               nullable=False)
    # ### end Alembic commands ###
